micronaut:
    function:
        name: rss-poller

jackson:
    bean-introspection-module: true
    date-format: "yyyy-MM-dd HH:mm:ss"

rss:
    feed:
        baseurl: https://www.bigscreen.com
        path: /xml/nowshowing_new.xml

sqs:
    queue:
        url: https://sqs.eu-central-1.amazonaws.com/804193320004/rssQueue
    message:
        batch-size: 40
        delay-between-batches: 15
